"""MO2017 prescribed-stabilizer orbit-MIS engine for C_7^box5 (Shannon capacity of C_7, n=5).

Graph: vertices = Z_7^5 (16807). u,v CONFUSABLE (adjacent) iff in EVERY coord
cdist(a,b)=min(|a-b|,7-|a-b|) <= 1. Independent set = no confusable pair.

A group element acts on a word x in Z_7^5 by: x -> P(x) + b mod 7, where P is a
coordinate permutation (in S_5) and b is a value-shift vector in Z_7^5.  A cyclic
group <g> generated by g=(P,b) acts; orbits partition the vertex set.  We pick a
set of orbits whose UNION is independent and maximize total size.

Verified against MO2017 350-set (order-7, P=id, b=(0,1,1,5,1)).
"""
import itertools, json, sys

N = 5
Q = 7

def cdist(a, b):
    d = abs(a - b) % Q
    return min(d, Q - d)

# precompute per-coord adjacency (cdist<=1)
CLOSE = [[1 if cdist(a, b) <= 1 else 0 for b in range(Q)] for a in range(Q)]

def confusable(u, v):
    for i in range(N):
        if not CLOSE[u[i]][v[i]]:
            return False
    return True

def apply_gen(x, perm, b):
    # x -> permute coords by perm, then add b
    return tuple((x[perm[i]] + b[i]) % Q for i in range(N))

def orbit_of(x, perm, b):
    """Return list of distinct words in the orbit of x under <(perm,b)>."""
    seen = []
    seenset = set()
    cur = x
    while cur not in seenset:
        seen.append(cur)
        seenset.add(cur)
        cur = apply_gen(cur, perm, b)
    return seen

def all_orbits(perm, b):
    """Partition all 7^5 words into orbits under <(perm,b)>. Returns list of orbits (each a tuple of words)."""
    seen = set()
    orbits = []
    for x in itertools.product(range(Q), repeat=N):
        if x in seen:
            continue
        orb = orbit_of(x, perm, b)
        for w in orb:
            seen.add(w)
        orbits.append(tuple(orb))
    return orbits

def orbit_internally_indep(orb):
    """True if no two DISTINCT words in the orbit are confusable."""
    L = len(orb)
    for i in range(L):
        for j in range(i + 1, L):
            if confusable(orb[i], orb[j]):
                return False
    return True

def build_conflict_graph(orbits):
    """Keep only internally-independent orbits. Build inter-orbit conflict edges:
    orbit i conflicts with orbit j if some word in i is confusable with some word in j.
    Returns (good_orbits, weights, adj) where adj[i] = set of conflicting orbit indices."""
    good = [o for o in orbits if orbit_internally_indep(o)]
    m = len(good)
    weights = [len(o) for o in good]
    # build a word->orbit map for efficiency, but conflicts need pairwise check.
    adj = [set() for _ in range(m)]
    # Use neighbor enumeration: for each word, its confusable neighbors are words within cdist<=1 in every coord.
    # Build orbit index per word.
    word_orbit = {}
    for idx, o in enumerate(good):
        for w in o:
            word_orbit[w] = idx
    # neighbor offsets: each coord in {-1,0,1} mod 7
    offsets = list(itertools.product((-1, 0, 1), repeat=N))
    for idx, o in enumerate(good):
        for w in o:
            for off in offsets:
                nb = tuple((w[i] + off[i]) % Q for i in range(N))
                if nb in word_orbit:
                    j = word_orbit[nb]
                    if j != idx:
                        adj[idx].add(j)
                        adj[j].add(idx)
    return good, weights, adj
