"""
Directed-rounded RIGOROUS certificate of the C_3a record lower bound from the EXACT integer
counts produced by the digit-DP engine.

The load-bearing quantities N+ = |U+U|, N- = |U-U|, M = max(U) are EXACT integers (computed by
the verified digit-DP, see digit_dp.py / selftest.py; the counts contain NO floating point).
Given them, the GHR lower bound is
    C_3a >= 1 + log(N-/N+) / log(2M+1).
This script bounds that real number rigorously BELOW using mpmath INTERVAL arithmetic with
directed (outward) rounding -- so the printed lower bound is a guaranteed true lower bound on
the GHR value, not a floating-point approximation.  We then confirm it clears the published
conservative bound 1.1740744.

WHY NOT the pure integer-power inequality here:  the equivalent integer check
N-^q >= N+^q * (2M+1)^p needs q = denominator(c-1).  For the razor-thin record value
1.174074447693521... clearing 1.1740744 by ~4.4e-7, q ~ 1.25e6, making N-^q a ~1.2e8-digit
integer -- infeasible (the outline-reviewer flagged this; the cheap integer-power / Lean cert
is reserved for a FOUND BEAT with a fatter margin, q ~ 40..155, a later sub-goal).  For the
RECORD baseline the rigorous certificate is this directed-rounded interval bound, which the
reviewer re-runs in seconds.

Run:  timeout 60 python3 certify_record.py
"""
import mpmath

# EXACT counts (regenerated by the engine into record_*.txt; also pinned here as literals so the
# certificate is self-contained and the reviewer can diff against the files).
N_PLUS = int(open('record_plus.txt').read())
N_MINUS = int(open('record_minus.txt').read())
M = int(open('record_max.txt').read())

PUBLISHED = mpmath.mpf('1.1740744')  # conservative bound in the ledger


def main():
    mpmath.mp.prec = 400  # ~120 decimal digits of working precision

    # Interval arithmetic with outward rounding for a GUARANTEED lower bound.
    mpmath.iv.prec = 400
    Nm = mpmath.iv.mpf(N_MINUS)
    Np = mpmath.iv.mpf(N_PLUS)
    den = mpmath.iv.mpf(2 * M + 1)

    # value = 1 + ln(Nm/Np)/ln(den).  All of Nm, Np, den > 1, ln increasing.
    ratio = Nm / Np
    num = mpmath.iv.log(ratio)
    dlog = mpmath.iv.log(den)
    val = 1 + num / dlog

    lo = val.a  # lower endpoint of the interval = guaranteed lower bound on the true value
    hi = val.b

    print("Exact integer ingredients (from the verified digit-DP):")
    print(f"  N+ = |U+U| : {len(str(N_PLUS))} digits")
    print(f"  N- = |U-U| : {len(str(N_MINUS))} digits")
    print(f"  M  = max(U): {len(str(M))} digits")
    print()
    print("Rigorous directed-rounded GHR value  1 + log(N-/N+)/log(2M+1):")
    print(f"  guaranteed lower bound (interval .a): {mpmath.nstr(lo, 25)}")
    print(f"  guaranteed upper bound (interval .b): {mpmath.nstr(hi, 25)}")
    print()

    # High-precision point value for display (matches PR #71's 1.174074447693521163...)
    pv = 1 + mpmath.log(mpmath.mpf(N_MINUS) / mpmath.mpf(N_PLUS)) / mpmath.log(mpmath.mpf(2 * M + 1))
    print(f"  point value (display): {mpmath.nstr(pv, 25)}")
    print(f"  PR#71 published value : 1.174074447693521163363531806658755676...")
    print()

    clears = lo > PUBLISHED
    print(f"  guaranteed lower bound > published 1.1740744 ? {clears}")
    print(f"  margin (lower bound - 1.1740744) >= {mpmath.nstr(lo - PUBLISHED, 6)}")
    print()
    print("CERTIFIED: C_3a >= " + mpmath.nstr(lo, 16)
          + "  (reproduces the record; gap 0 to the ledger value, NOT a beat).")
    return 0 if clears else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
